version: '3'
services:
  client:
    image: node:latest
    ports: 
      - 3000:3000
    volumes:
      - type: bind
        source: ./client
        target: /code
    working_dir: /code
    command: bash -c "npm install && npm run dev"
  server:
    image: node:latest
    volumes:
      - type: bind
        source: ./server
        target: /code
    working_dir: /code
    ports:
      - 5000:5000
    environment:
      - PGUSER=maximon
      - PGHOST=db
      - PGPASSWORD=secretpassword2
      - PGDATABASE=memoriaes
      - PGPORT=5432
    command: bash -c "npm install && npm run seedDev && npm run dev"
    depends_on: 
      - db
  db:
    image: postgres:latest
    volumes:
      - 'postgresdata:/var/lib/postgresql/data'
      - './db:/docker-entrypoint-initdb.d/:ro'
    environment:
      - POSTGRES_PASSWORD=secretpassword2
      - POSTGRES_USER=maximon
      - POSTGRES_DB=memoriaes
volumes:
  postgresdata:
